from dotenv import load_dotenv
import os

load_dotenv()

ACCESS_TOKEN = os.getenv("LINKEDIN_ACCESS_TOKEN")
PERSON_URN = os.getenv("LINKEDIN_PERSON_URN")

CLIENT_ID = os.getenv("LINKEDIN_CLIENT_ID")
CLIENT_SECRET = os.getenv("LINKEDIN_CLIENT_SECRET")

FACEBOOK_PAGE_ID = os.getenv("FACEBOOK_PAGE_ID")
FACEBOOK_ACCESS_TOKEN = os.getenv("FACEBOOK_ACCESS_TOKEN")

DOUWE_ACCESS_TOKEN = os.getenv("DOUWE_ACCESS_TOKEN")
DOUWE_PERSON_URN = os.getenv("DOUWE_PERSON_URN")
DOUWE_CLIENT_ID = os.getenv("DOUWE_CLIEND_ID")
DOUWE_CLIENT_SECRET = os.getenv("DOUWE_CLIENT_SECRET")